# via:https://phus.lu/nginx.conf
server {
	listen 443 ssl;
	listen [::]:443 ssl;
	listen 443 quic;
	listen [::]:443 quic;
	server_name file.example.com;
	root /html/file;

	include /etc/nginx/conf.d/config.ssl;
	# include /etc/nginx/conf.d/config.cloudflare; # 使用 Cloudflare 取消此项注释

	log_not_found off;
	client_max_body_size 4G;
	charset utf-8,gbk;

	location = / {
		autoindex on;
		autoindex_exact_size off;
		autoindex_localtime on;
		add_after_body "/autoindex.html";
	}

	location = /ssh.pub {
		default_type text/plain;
		add_header x-ssh-import "curl -sS files.sss.red/ssh.pub | tee -a  ~/.ssh/authorized_keys";
		try_files /ssh.pub =404;
	}

	location = /generate_204 {
		return 204;
	}

	location /dav/ {
		dav_methods PUT DELETE MKCOL COPY MOVE;
		# dav_ext_methods PROPFIND OPTIONS;
		create_full_put_path on;
		dav_access user:rw group:rw all:r;
	}

	location /tmp/ {
		alias /tmp/;
	}

	location ~ ^/speech/.+\.md$ {
		default_type text/html;
		add_after_body /.theme/markdown.html;
	}

	location ~* \.(ico|css|gif|jpeg|jpg|png|woff|ttf|otf|svg|woff2|eot)$ {
		expires 1d;
		access_log off;
		add_header Pragma public;
	}

	location ~ \.(md|log|pac|keys|lua|json|yaml|toml|conf|cmd|sh|bash|h|c|cpp|hpp|py|go|service|dockerfile)$ {
		default_type text/plain;
	}

	location ~ ^/(bashrc|vimrc|server/ipinfo)$ {
		default_type text/plain;
	}

	location ~ ^/\.(?!well-known).* {
		deny all;
		access_log off;
		error_log /dev/null crit;

	}

	location ~ ^/(sing/) {
		auth_basic "Please Login In";
		auth_basic_user_file /html/file/.htpasswd;
		autoindex on;
		autoindex_exact_size off;
		autoindex_localtime on;
		add_after_body "/autoindex.html";
	}

	resolver 8.8.8.8 1.1.1.1 valid=300s;
	resolver_timeout 5s;
	location /get_ip {
		proxy_pass https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr?ip=$remote_addr;
		proxy_set_header Host api.live.bilibili.com;
	}

	location ~ ^(.*)/$ {
		autoindex on;
		autoindex_exact_size off;
		autoindex_localtime on;
		add_after_body "/autoindex.html";
	}

	access_log /var/log/nginx/file.log json_format;
	error_log /var/log/nginx/error.file.log;
}