map $host $backend {
	vaultwarden.example.com 127.0.10.2:9999;
	aria2.example.com 127.0.10.3:9999;
	alist.example.com 127.0.10.4:9999;
	jellyfin.example.com 127.0.10.5:9999;
	file.example.com unix:/dev/shm/filebrowser/filebrowser.socket;
	drive.example.com unix:/dev/shm/cloudreve/cloudreve.socket;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	listen 443 quic;
	listen [::]:443 quic;
	server_name ~^(?<subdomain>vaultwarden|aria2|alist|jellyfin|file|drive)\.example\.com$;

	include /etc/nginx/conf.d/config.ssl;
	# include /etc/nginx/conf.d/config.cloudflare; # 使用 Cloudflare 取消此项注释
	client_max_body_size 525M;

	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_ssl_server_name on;
		proxy_redirect off;

		proxy_buffers 16 256K;
		proxy_pass http://$backend;
	}

	# 此处日志动态创建，可能需要修改日志目录权限
	access_log /var/log/nginx/$host.log json_format;
	error_log /var/log/nginx/error.proxy.log;
}
