server {
	listen 443 ssl;
	listen [::]:443 ssl;
	listen 443 quic;
	listen [::]:443 quic;
	server_name vaultwarden.example.com;

	include /etc/nginx/conf.d/config.ssl;
	# include /etc/nginx/conf.d/config.cloudflare; # 使用 Cloudflare 取消此项注释
	client_max_body_size 525M;

	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_ssl_server_name on;
		proxy_redirect off;

		proxy_pass http://vaultwarden-default;
	}

	access_log /var/log/nginx/vaultwarden.log json_format;
}
