server_tokens off;
autoindex off;
proxy_hide_header X-Powered-By;
fastcgi_hide_header X-Powered-By;
include /etc/nginx/conf.d/ip.blacklist;

server {
	listen 80 default_server;
	listen [::]:80 default_server;

	location / {
		return 301 https://$host$request_uri;
	}
}

server {
	listen 443 ssl default_server reuseport;
	listen [::]:443 ssl default_server reuseport;
	listen 443 quic default_server reuseport;
	listen [::]:443 quic default_server reuseport;
	server_name _;
	root /html/default;

	include /etc/nginx/conf.d/config.ssl;

	access_log /var/log/nginx/default.log;
}
