# via:https://www.chenhuazhan.com/ui/details/169

# 定义一个变量来存储年月日
map $time_iso8601 $date {
	default "date-not-found";
	'~^(?<ymd>\d{4}-\d{2}-\d{2})' $ymd;
}

# 定义一个变量来存储时分秒
map $time_iso8601 $time {
	default "time-not-found";
	'~T(?<hms>\d{2}:\d{2}:\d{2})' $hms;
}

# 定义日志格式为json格式
log_format json_format '{
	"timestamp": "$date $time",
	"remote_addr": "$remote_addr",
	"remote_user": "$remote_user",
	"request": "$request",
	"status": "$status",
	"body_bytes_sent": "$body_bytes_sent",
	"http_referer": "$http_referer",
	"http_user_agent": "$http_user_agent",
	"http_x_forwarded_for": "$http_x_forwarded_for"
},';

# 定义一个变量来存储年月,可用来作为access.log的日志文件名，按月自动分割日志
map $time_iso8601 $logmonth {
	'~^(?<ym>\d{4}-\d{2})' $ym;
	default 'date-not-found';
}

# 定义一个变量来存储年月日，可用来作为access.log的日志文件名，按天自动分割日志
map $time_iso8601 $logdate {
	'~^(?<ymd>\d{4}-\d{2}-\d{2})' $ymd;
	default 'date-not-found';
}

# 开启access.log日志，可设置日志名变量(这里选择上面的按天)以便分割日志；可设置日志格式，以便更直观分析日志
access_log logs/access-$logdate.log json_format;
